### ISSUE TITLE
Api level override warning

### ISSUE THREAD

**Issue by MidoriKami** [goatcorp/DalamudPluginsD17#2373]
Bleatbot should complain during the build process if a manifest contains a apilevel override.

Dalamud packager should be responsible for setting the correct apilevel

**Comment by PunishedPineapple** [comment]
I commented on a PR where this was brought up, but I see that it's here, so I will just repeat what I said there:
> Doesn't this run a bit counter to the point of having the API level specified? At that point it basically just becomes a packager version check, not whether the plugin is intended to be a specific API level. Generally, the other manifest fields that the packager inserts are taken from what your code states that it is (i.e., assemby version and internal name), and not assumed by the packager like the API level is (besides loading parameters, which I am guessing few people use, but maybe I am wrong).

Specifying the API level shows the intention rather than just that you updated the packager package, imo.

**Comment by MidoriKami** [comment]
I still think this would be a good idea to disallow, but will close this issue as the build system in the end prevents you from building an invalid api version.
