### ISSUE TITLE
Waymark Plugin not working correctly? 

### ISSUE THREAD

**Issue by iUngaBunga** [goatcorp/DalamudPluginsD17#2767]
I am unable to import waymarks from my current in game saved waymarks? is this plugin no longer working?

**Comment by Blooym** [comment]
This isn't the place to report bugs with individual plugins. 

If you'd like to report a bug for "Waymark Preset Plugin" you can find it's repository [here](https://github.com/Infiziert90/WaymarkPresetPlugin), or you can ask in the plugin's thread on Discord [here](https://discord.gg/holdshift).
