### ISSUE TITLE
Plogon fails don't actually error the action

### ISSUE THREAD

**Issue by goaaats** [goatcorp/DalamudPluginsD17#4]
It sets the exit code to -1, but that doesn't work?

**Comment by NotNite** [comment]
Doing `Environment.Exit(1)` instead of setting `Environment.ExitCode` seemed to work, not sure if this is a bad thing but we're at the end of execution anyways, right?

**Comment by NotNite** [comment]
![image](https://user-images.githubusercontent.com/44414597/181995928-9491436c-2527-4595-ae78-01a7bed8bba1.png)
I have 300 iq.
