### ISSUE TITLE
Remove testing/net6

### ISSUE THREAD

**Issue by philpax** [goatcorp/DalamudPluginsD17#668]
I think we can safely say that all the plugins that were going to be ported have been ported by now. Making an issue, not a PR, as I don't know if other parts of the build system need to be changed to do this. (Might be nice to have docs on adding or removing test channels?)

**Comment by goaaats** [comment]
Did dun did it, in the future I'd love to have per-plugin testing branches that can be specified in the manifest and keep the testing/X branches for entire ecosystem switchovers(e.g. api level bump, .net version)
